name: Run Cypress Tests

on:
  workflow_dispatch:
  push:
    paths:
      - webtester/web-cypress/**
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            sparse-checkout: webtester/web-cypress
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: webtester/web-cypress
          browser: chrome
          