name: Playwright Tests
on:
  workflow_dispatch:
  push:
    paths:
      - webtester/web-playwright/**
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
          sparse-checkout: webtester/web-playwright
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
          cd webtester/web-playwright
          npm ci
    - name: Install Playwright Browsers
      run: |
          cd webtester/web-playwright
          npx playwright install --with-deps
    - name: Run type checks
      run: |
          cd webtester/web-playwright
          npx tsc -p tsconfig.json --noEmit
    - name: Run Playwright tests
      run: |
          cd webtester/web-playwright
          npx playwright test --trace on
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: webtester/web-playwright/playwright-report/
        retention-days: 10