name: Validate new git push on MovieDB python project   
  
on:
  workflow_dispatch:
  push:  
    paths:
      - apitester/pytest-bdd-moviedb/**
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.12"]  
  
    steps:  
      - uses: actions/checkout@v4.2.0  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v5.2.0  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip 
          if [ -f apitester/pytest-bdd-moviedb/requirements.txt ]; then pip install -r apitester/pytest-bdd-moviedb/requirements.txt; fi  
      - name: Run Movie Smoke tests - pytest 
        run: |
          cd apitester/pytest-bdd-moviedb  
          pytest -m smoke
